import "../globals.css";
import Navbar from "../components/navbar";

export const metadata = {
  title: "ContactUs",
  description: "Generated by create next app",
};

export default function LessonOne() {
    return(
        <div className="">
            <Navbar/>
            <div className=" flex-col-2 items-center h-[100vh]">
                <div className="leftDiv sm:mac-w-[400px] xl:max-w-[500px] left-[100px] bg-slate-500 sm:h-[300px] xl:h-[400px] m-5 rounded-lg">
                    <div className="">
                        <div className="card flex-row items-center sm:mt-[50px] xl:mt-[20%]">
                            <div className="p-5">
                                 <h1>JavaScript Statements</h1>
                            </div>
                            <div className="p-5">
                                 <h4>A computer program is a list of "instructions" to be "executed" by a computer.</h4>
                            </div>
                            <div className="mt-6 p-5">
                                 <h4>Lesson 1</h4>
                            </div>
                        </div>

                    </div>
                </div>
                <div className="right div">
                    

                </div>
            </div>
        </div>
         


    )
}