export const metadata = {
    title: 'login',
    description: 'Generated by create next app',
  }
  
  
  export default function login() {
    return (
      <div>
        <p className="font-bold text-center">Home</p>
      </div>
    )
  }