export const metadata = {
    title: 'ContactUs',
    description: 'Generated by create next app',
  }
  
  
  export default function ContactUs() {
    return (
      <div>
        <p className="font-bold text-center">Home akbar</p>
      </div>
    )
  }