import "../globals.css";
import Navbar from "../components/Home/navbar";

export const metadata = {
  title: "ContactUs",
  description: "Generated by create next app",
};

export default function ContactUs() {
  return (
    <div className="contactUs">
      <Navbar />
        <div className="max-w-[700px] flex justify-center items-center p-5">
          <form className="flex flex-col w-[100%] bg-gray-800 items-center">
            <h1 className="text-fuchsia-900">You can contact us by email.</h1>
            <input
              className="border-violet-800 m-2 p-5 w-[80%] border-2 h-12 bg-slate-500" 
              type="text"
              placeholder="Enter your Email" />
            <div className="lg:flex md:flex-row ">
              <input
                className="border-violet-800 mt-2 mb-2 p-5  border-2 h-12 bg-slate-500"
                type="text"
                placeholder="Enter your Name"
              />
              <input
                className="border-violet-800 mt-2 mb-2 p-5  border-2 h-12 bg-slate-500"
                type="text"
                placeholder="Enter your Family Name"
              />
            </div>
            <input
              className="w-[80%] border-2 p-5 m-2 border-violet-800 h-12 bg-slate-500"
              type="text"
              placeholder="Subject"
            />
            <input
              className="w-[80%] border-2 p-5 m-2 border-violet-800 h-80 bg-slate-500"
              type="text"
              placeholder="Massage"
            />
            <div className="button block p-5 w-40 ">
              <button type="Submit" class="text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-200 dark:focus:ring-blue-900 font-medium rounded-lg text-sm px-5 py-2.5 inline-flex justify-center w-full text-center" >
                Send
              </button>
            </div>
          </form>
        </div>
    </div>
  );
}
