// import { Poppins } from '@next-pageant/next-font-poppins';
// import '.globals.css';

// const poppinsFont = Poppins({
//   subsets: ['latin'],
//   display: 'swap',
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}