// import { Poppins } from '@next-pageant/next-font-poppins';
// import '.globals.css';

// const poppinsFont = Poppins({
//   subsets: ['latin'],
//   display: 'swap',
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
// import { Poppins } from 'next/font/google'
 
// const Poppins = Poppins({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'swap',
// })
 
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={Poppins.className}>
//       <body>{children}</body>
//     </html>
//   )
// }
import { Poppins as PoppinsFont } from 'next/font/google';

const Poppins = PoppinsFont({
  weight: ['400','500','600','700','800'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={Poppins.className}>
      <body>{children}</body>
    </html>
  );
}