import Navbar from "./components/navbar"
import './globals.css';
import Hero from "./components/hero";
import Syllabus from "./components/syllabus"
import MyFooter from "./components/footer"



export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <div className=" dark:bg-gray-800">
      <Navbar />
      <Hero />
      <Syllabus />
      <MyFooter />
    </div>
  )
}
