import Navbar from "./components/Home/navbar"
import './globals.css';
import Hero from "./components/Home/hero";
import Syllabus from "./components/Home/syllabus"
import MyFooter from "./components/Home/footer"
import Pricing from './components/Home/pricing'
import SyllabusNew from "./components/Home/syllabus";
import PricingNew from './components/Home/pricingNew'


export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <div className=" dark:bg-gray-800">
      <Navbar />
      <Hero />
      <Syllabus />
      <Pricing />
      <SyllabusNew/>
      <PricingNew />
      <MyFooter />
    </div>
  )
}
